# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)


DESCRIPTOR = _descriptor.FileDescriptor(
    name='messages.proto',
    package='proto',
    serialized_pb='\n\x0emessages.proto\x12\x05proto\"b\n\x0b\x62inary_mesh\x12\"\n\x05\x63hunk\x18\x01 \x03(\x0b\x32\x13.proto.chunk_simple\x12/\n\x0fquantized_chunk\x18\x02 \x03(\x0b\x32\x16.proto.chunk_quantized\"2\n\x0fvertices_simple\x12\x0f\n\x03xyz\x18\x01 \x03(\x02\x42\x02\x10\x01\x12\x0e\n\x02uv\x18\x02 \x03(\x02\x42\x02\x10\x01\"!\n\x0c\x66\x61\x63\x65s_simple\x12\x11\n\x05\x66\x61\x63\x65s\x18\x01 \x03(\rB\x02\x10\x01\"\x87\x01\n\x0c\x63hunk_simple\x12(\n\x08vertices\x18\x01 \x01(\x0b\x32\x16.proto.vertices_simple\x12\"\n\x05\x66\x61\x63\x65s\x18\x02 \x01(\x0b\x32\x13.proto.faces_simple\x12\x12\n\nchunk_name\x18\x03 \x01(\t\x12\x15\n\rmaterial_name\x18\x04 \x01(\t\"l\n\x12vertices_quantized\x12\x14\n\x0cquantization\x18\x01 \x01(\x02\x12\x13\n\x0btranslation\x18\x02 \x03(\x02\x12\r\n\x01x\x18\x03 \x03(\x11\x42\x02\x10\x01\x12\r\n\x01y\x18\x04 \x03(\x11\x42\x02\x10\x01\x12\r\n\x01z\x18\x05 \x03(\x11\x42\x02\x10\x01\"P\n\x0cuv_quantized\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0cquantization\x18\x02 \x01(\x02\x12\r\n\x01u\x18\x03 \x03(\x11\x42\x02\x10\x01\x12\r\n\x01v\x18\x04 \x03(\x11\x42\x02\x10\x01\"%\n\x10\x66\x61\x63\x65s_compressed\x12\x11\n\x05\x66\x61\x63\x65s\x18\x01 \x03(\x11\x42\x02\x10\x01\"\xaf\x01\n\x0f\x63hunk_quantized\x12\x12\n\nchunk_name\x18\x01 \x01(\t\x12\x15\n\rmaterial_name\x18\x02 \x01(\t\x12+\n\x08vertices\x18\x03 \x01(\x0b\x32\x19.proto.vertices_quantized\x12 \n\x03uvs\x18\x04 \x03(\x0b\x32\x13.proto.uv_quantized\x12\"\n\x05\x66\x61\x63\x65s\x18\x05 \x01(\x0b\x32\x13.proto.faces_simple')

_BINARY_MESH = _descriptor.Descriptor(
    name='binary_mesh',
    full_name='proto.binary_mesh',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='chunk', full_name='proto.binary_mesh.chunk', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='quantized_chunk', full_name='proto.binary_mesh.quantized_chunk', index=1,
            number=2, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=25,
    serialized_end=123,
)

_VERTICES_SIMPLE = _descriptor.Descriptor(
    name='vertices_simple',
    full_name='proto.vertices_simple',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='xyz', full_name='proto.vertices_simple.xyz', index=0,
            number=1, type=2, cpp_type=6, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
        _descriptor.FieldDescriptor(
            name='uv', full_name='proto.vertices_simple.uv', index=1,
            number=2, type=2, cpp_type=6, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=125,
    serialized_end=175,
)

_FACES_SIMPLE = _descriptor.Descriptor(
    name='faces_simple',
    full_name='proto.faces_simple',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='faces', full_name='proto.faces_simple.faces', index=0,
            number=1, type=13, cpp_type=3, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=177,
    serialized_end=210,
)

_CHUNK_SIMPLE = _descriptor.Descriptor(
    name='chunk_simple',
    full_name='proto.chunk_simple',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='vertices', full_name='proto.chunk_simple.vertices', index=0,
            number=1, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='faces', full_name='proto.chunk_simple.faces', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='chunk_name', full_name='proto.chunk_simple.chunk_name', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=u'',
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='material_name', full_name='proto.chunk_simple.material_name', index=3,
            number=4, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=u'',
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=213,
    serialized_end=348,
)

_VERTICES_QUANTIZED = _descriptor.Descriptor(
    name='vertices_quantized',
    full_name='proto.vertices_quantized',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='quantization', full_name='proto.vertices_quantized.quantization', index=0,
            number=1, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='translation', full_name='proto.vertices_quantized.translation', index=1,
            number=2, type=2, cpp_type=6, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='x', full_name='proto.vertices_quantized.x', index=2,
            number=3, type=17, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
        _descriptor.FieldDescriptor(
            name='y', full_name='proto.vertices_quantized.y', index=3,
            number=4, type=17, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
        _descriptor.FieldDescriptor(
            name='z', full_name='proto.vertices_quantized.z', index=4,
            number=5, type=17, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=350,
    serialized_end=458,
)

_UV_QUANTIZED = _descriptor.Descriptor(
    name='uv_quantized',
    full_name='proto.uv_quantized',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='name', full_name='proto.uv_quantized.name', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=u'',
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='quantization', full_name='proto.uv_quantized.quantization', index=1,
            number=2, type=2, cpp_type=6, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='u', full_name='proto.uv_quantized.u', index=2,
            number=3, type=17, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
        _descriptor.FieldDescriptor(
            name='v', full_name='proto.uv_quantized.v', index=3,
            number=4, type=17, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=460,
    serialized_end=540,
)

_FACES_COMPRESSED = _descriptor.Descriptor(
    name='faces_compressed',
    full_name='proto.faces_compressed',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='faces', full_name='proto.faces_compressed.faces', index=0,
            number=1, type=17, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=542,
    serialized_end=579,
)

_CHUNK_QUANTIZED = _descriptor.Descriptor(
    name='chunk_quantized',
    full_name='proto.chunk_quantized',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='chunk_name', full_name='proto.chunk_quantized.chunk_name', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=u'',
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='material_name', full_name='proto.chunk_quantized.material_name', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=u'',
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='vertices', full_name='proto.chunk_quantized.vertices', index=2,
            number=3, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='uvs', full_name='proto.chunk_quantized.uvs', index=3,
            number=4, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='faces', full_name='proto.chunk_quantized.faces', index=4,
            number=5, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=582,
    serialized_end=757,
)

_BINARY_MESH.fields_by_name['chunk'].message_type = _CHUNK_SIMPLE
_BINARY_MESH.fields_by_name['quantized_chunk'].message_type = _CHUNK_QUANTIZED
_CHUNK_SIMPLE.fields_by_name['vertices'].message_type = _VERTICES_SIMPLE
_CHUNK_SIMPLE.fields_by_name['faces'].message_type = _FACES_SIMPLE
_CHUNK_QUANTIZED.fields_by_name['vertices'].message_type = _VERTICES_QUANTIZED
_CHUNK_QUANTIZED.fields_by_name['uvs'].message_type = _UV_QUANTIZED
_CHUNK_QUANTIZED.fields_by_name['faces'].message_type = _FACES_SIMPLE
DESCRIPTOR.message_types_by_name['binary_mesh'] = _BINARY_MESH
DESCRIPTOR.message_types_by_name['vertices_simple'] = _VERTICES_SIMPLE
DESCRIPTOR.message_types_by_name['faces_simple'] = _FACES_SIMPLE
DESCRIPTOR.message_types_by_name['chunk_simple'] = _CHUNK_SIMPLE
DESCRIPTOR.message_types_by_name['vertices_quantized'] = _VERTICES_QUANTIZED
DESCRIPTOR.message_types_by_name['uv_quantized'] = _UV_QUANTIZED
DESCRIPTOR.message_types_by_name['faces_compressed'] = _FACES_COMPRESSED
DESCRIPTOR.message_types_by_name['chunk_quantized'] = _CHUNK_QUANTIZED


def _chunks(l, n):
    for i in range(0, len(l), n):
        yield l[i:i + n]


class binary_mesh(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _BINARY_MESH

    # @@protoc_insertion_point(class_scope:proto.binary_mesh)


class vertices_simple(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _VERTICES_SIMPLE

    # @@protoc_insertion_point(class_scope:proto.vertices_simple)


class faces_simple(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _FACES_SIMPLE

    # @@protoc_insertion_point(class_scope:proto.faces_simple)


class chunk_simple(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _CHUNK_SIMPLE

    # @@protoc_insertion_point(class_scope:proto.chunk_simple)


class vertices_quantized(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _VERTICES_QUANTIZED

    # @@protoc_insertion_point(class_scope:proto.vertices_quantized)


class uv_quantized(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _UV_QUANTIZED

    # @@protoc_insertion_point(class_scope:proto.uv_quantized)


class faces_compressed(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _FACES_COMPRESSED

    # @@protoc_insertion_point(class_scope:proto.faces_compressed)


class chunk_quantized(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _CHUNK_QUANTIZED

    # @@protoc_insertion_point(class_scope:proto.chunk_quantized)


_VERTICES_SIMPLE.fields_by_name['xyz'].has_options = True
_VERTICES_SIMPLE.fields_by_name['xyz']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_VERTICES_SIMPLE.fields_by_name['uv'].has_options = True
_VERTICES_SIMPLE.fields_by_name['uv']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_FACES_SIMPLE.fields_by_name['faces'].has_options = True
_FACES_SIMPLE.fields_by_name['faces']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_VERTICES_QUANTIZED.fields_by_name['x'].has_options = True
_VERTICES_QUANTIZED.fields_by_name['x']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_VERTICES_QUANTIZED.fields_by_name['y'].has_options = True
_VERTICES_QUANTIZED.fields_by_name['y']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_VERTICES_QUANTIZED.fields_by_name['z'].has_options = True
_VERTICES_QUANTIZED.fields_by_name['z']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_UV_QUANTIZED.fields_by_name['u'].has_options = True
_UV_QUANTIZED.fields_by_name['u']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_UV_QUANTIZED.fields_by_name['v'].has_options = True
_UV_QUANTIZED.fields_by_name['v']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_FACES_COMPRESSED.fields_by_name['faces'].has_options = True
_FACES_COMPRESSED.fields_by_name['faces']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(),
                                                                               '\020\001')
# @@protoc_insertion_point(module_scope)
